In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("fullset.csv", encoding="latin-1")
df.drop(df.columns[0], axis=1, inplace=True) # Dropping the real names column for privacy
df.head()

       Pseudonym  Midterm_Pass  Final_Pass  ...  Trait_12  Trait_13  Trait_14
0  First_Medical             1           1  ...       3.0         3       2.0
1     Stolen_Zip             1           1  ...       1.0         2       2.0
2   Scout_Korean             1           1  ...       2.0         4       1.0
3  Curly_Russian             1           1  ...       3.0         4       1.0
4   Doctor_Piano             1           1  ...       5.0         3       2.0

[5 rows x 18 columns]

In [8]:
print("Dataframe shape is " + str(df.shape))
print("Dataframe columns are " + str(df.columns.tolist()))

Dataframe shape is (110, 18)
Dataframe columns are ['Pseudonym', 'Midterm_Pass', 'Final_Pass', 'Attend_IRL', 'Trait_1', 'Trait_2', 'Trait_3', 'Trait_4', 'Trait_5', 'Trait_6', 'Trait_7', 'Trait_8', 'Trait_9', 'Trait_10', 'Trait_11', 'Trait_12', 'Trait_13', 'Trait_14']

In [16]:
df.isnull().mean().sort_values(ascending=False)

Trait_8         0.754545
Trait_14        0.736364
Trait_6         0.372727
Trait_4         0.354545
Trait_11        0.336364
Trait_9         0.327273
Trait_3         0.272727
Trait_12        0.272727
Trait_7         0.072727
Trait_2         0.036364
Midterm_Pass    0.000000
Pseudonym       0.000000
Attend_IRL      0.000000
Trait_1         0.000000
Trait_5         0.000000
Final_Pass      0.000000
Trait_10        0.000000
Trait_13        0.000000
dtype: float64

In [27]:
from sklearn.impute import SimpleImputer
df.drop(df.columns[0], axis=1, inplace=True) # Dropping the first column because it is non-numerical
imputer = SimpleImputer(strategy='median')
df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
df.head(20)

    Trait_2  Trait_3  Trait_4  Trait_5  ...  Trait_11  Trait_12  Trait_13  Trait_14
0       3.0      3.0      2.0        5  ...       4.0       3.0         3       2.0
1       5.0      2.0      4.0        2  ...       3.0       1.0         2       2.0
2       3.0      4.0      4.0        5  ...       1.0       2.0         4       1.0
3       1.0      4.0      3.0        4  ...       5.0       3.0         4       1.0
4       4.0      5.0      1.0        3  ...       2.0       5.0         3       2.0
5       5.0      1.0      4.0        4  ...       4.0       2.0         5       2.0
6       3.0      2.0      2.0        2  ...       2.0       1.0         1       2.0
7       4.0      4.0      3.0        3  ...       4.0       2.0         1       1.0
8       2.0      2.0      4.0        2  ...       5.0       3.0         1       1.0
9       2.0      1.0      4.0        2  ...       4.0       3.0         5       1.0
10      1.0      2.0      1.0        1  ...       4.0       2.0         2       1.0
11      5.0      5.0      4.0        4  ...       3.0       4.0         5       4.0
12      2.0      2.0      4.0        5  ...       4.0       1.0         5       3.0
13      5.0      4.0      5.0        4  ...       5.0       3.0         5       5.0
14      2.0      2.0      2.0        3  ...       3.0       1.0         3       2.0
15      4.0      2.0      3.0        2  ...       5.0       3.0         4       2.0
16      2.0      4.0      4.0        5  ...       5.0       1.0         4       1.0
17      4.0      1.0      1.0        1  ...       5.0       3.0         1       NaN
18      3.0      3.0      3.0        1  ...       3.0       3.0         1       NaN
19      1.0      4.0      1.0        1  ...       2.0       1.0         1       NaN

[20 rows x 13 columns]

In [31]:
df_numeric = df.select_dtypes(include='number')
df_imputed = pd.DataFrame(imputer.fit_transform(df_numeric), columns=df_numeric.columns)

df.head(20)

    Trait_2  Trait_3  Trait_4  Trait_5  ...  Trait_11  Trait_12  Trait_13  Trait_14
0       3.0      3.0      2.0        5  ...       4.0       3.0         3       2.0
1       5.0      2.0      4.0        2  ...       3.0       1.0         2       2.0
2       3.0      4.0      4.0        5  ...       1.0       2.0         4       1.0
3       1.0      4.0      3.0        4  ...       5.0       3.0         4       1.0
4       4.0      5.0      1.0        3  ...       2.0       5.0         3       2.0
5       5.0      1.0      4.0        4  ...       4.0       2.0         5       2.0
6       3.0      2.0      2.0        2  ...       2.0       1.0         1       2.0
7       4.0      4.0      3.0        3  ...       4.0       2.0         1       1.0
8       2.0      2.0      4.0        2  ...       5.0       3.0         1       1.0
9       2.0      1.0      4.0        2  ...       4.0       3.0         5       1.0
10      1.0      2.0      1.0        1  ...       4.0       2.0         2       1.0
11      5.0      5.0      4.0        4  ...       3.0       4.0         5       4.0
12      2.0      2.0      4.0        5  ...       4.0       1.0         5       3.0
13      5.0      4.0      5.0        4  ...       5.0       3.0         5       5.0
14      2.0      2.0      2.0        3  ...       3.0       1.0         3       2.0
15      4.0      2.0      3.0        2  ...       5.0       3.0         4       2.0
16      2.0      4.0      4.0        5  ...       5.0       1.0         4       1.0
17      4.0      1.0      1.0        1  ...       5.0       3.0         1       NaN
18      3.0      3.0      3.0        1  ...       3.0       3.0         1       NaN
19      1.0      4.0      1.0        1  ...       2.0       1.0         1       NaN

[20 rows x 13 columns]

In [32]:
# See which columns are fully empty
print("Fully NaN columns:")
print(df_numeric.columns[df_numeric.isnull().all()].tolist())

# See % missing per column
print("\nMissing % per column:")
print(df_numeric.isnull().mean().sort_values(ascending=False).head(10))

Fully NaN columns:
[]

Missing % per column:
Trait_8     0.754545
Trait_14    0.736364
Trait_6     0.372727
Trait_4     0.354545
Trait_11    0.336364
Trait_9     0.327273
Trait_12    0.272727
Trait_3     0.272727
Trait_7     0.072727
Trait_2     0.036364
dtype: float64